protected/controllers/AccountController.php
<?php

class AccountController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return [
            // allow all users to perform 'index' and 'view' actions
            [
                'allow',
                'actions' => ['createGuest','create'],
                'users' => ['*'],
            ],
            // allow authenticated user to perform 'create' and 'update' actions
            [
                'allow',
                'actions' => ['updateID', 'indexID', 'viewID','view'],
                'users' => ['@'],
            ],
            // allow admin user to perform 'admin' and 'delete' actions
            [
                'allow',
                'users' => ['superadmin'],
            ],
            // deny all users
            [
                'deny',
                'actions' => ['updateID', 'indexID', 'viewID','view'],
                'users' => ['*'],
            ],
        ];
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        if($id === Yii::app()->user->id || Yii::app()->user->isSuperAdmin()){
        // if($id === Yii::app()->user->id){
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
        } else {
            throw new CHttpException(403,'You are not authorized to perform this action.');
        }
    }

    public function actionViewID() {

        $this->render('viewID', array(
            'model' => $this->loadModel(Yii::app()->user->id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreateGuest() {
        $model = new Account;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        //LOGIN RULE
        if (isset($_POST['Account'])) {
            $model->attributes = $_POST['Account'];
            $model->NoMatrik = strtoupper($model->NoMatrik);
            $model->NoIC = strtoupper($model->NoIC);
            $model->role = 'voter';

            Account::checkMatric($model);

            if ($model->save()) {
                $modelLogin = new LoginForm;
                $modelLogin->username = $model->NoMatrik;
                $modelLogin->password = $model->NoIC;
                if($model->validate() && $modelLogin->login())
                    $this->redirect(array('viewID'));
//                    $this->redirect(array('index'));
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    public function actionCreate() {
        $model = new Account;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Account'])) {
            $model->attributes = $_POST['Account'];
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->ID));
//                    $this->redirect(array('index'));
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Account'])) {
            $model->attributes = $_POST['Account'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->ID));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    public function actionUpdateID() {
        $model = $this->loadModel(Yii::app()->user->id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Account'])) {
            $model->attributes = $_POST['Account'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->ID));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Account');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }


    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Account('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Account']))
            $model->attributes = $_GET['Account'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    public function actionAdminIndex() {
        $model = new Account('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Account']))
            $model->attributes = $_GET['Account'];

        $this->renderPartial('admin', array(
            'model' => $model,
        ));
    }

    public function actionAdminView() {
        $model = new Account('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Account']))
            $model->attributes = $_GET['Account'];

        $this->renderPartial('adminView', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Account the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Account::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Account $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'account-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="language" content="en">

        <!-- blueprint CSS framework -->
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection">
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
        <!--[if lt IE 8]>
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
        <![endif]-->

        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">

        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
        <style>
            /*.outer{
                background-color: thistle;
            }*/

            .bg{
                padding:0px;
                /*height: 100%; */
				/*background-color:transparent;*/
            }
        </style>
    </head>


    <body  class="outer">

        <div class="container" id="page">

            <div id="header" style="padding:0px">
                <div id="logo" class="bg" style="padding:0px 0px">                      <!-- BANNER -->
                    <?php  CHtml::image(Yii::app()->baseUrl . "/images/undi/web_4x10-picom.PNG","",array("style"=>"width:100%;height:250px;")); ?>
                    <?php  echo CHtml::image(Yii::app()->baseUrl . "/images/election.jpg","",array("style"=>"width:100%;")); ?>
                </div>


            </div> <!-- header -->

            <div id="mainmenu" style="padding-top:0px">
                <?php
                $this->widget('zii.widgets.CMenu', array(
                'items' => array(
                array('label' => 'Home', 'url' => array('/site/index')),
                array('label' => 'Vote', 'url' => array('/mppList/adminVoter'), 'visible' => Yii::app()->user->isVoter()),
                array('label' => 'Manage MPP', 'url' => array('/mppList/admin'), 'visible' => Yii::app()->user->isSuperAdmin()),
                array('label' => 'Manage User Account', 'url' => array('/account/admin'), 'visible' => Yii::app()->user->isSuperAdmin()),
                array('label' => 'Manage Account', 'url' => array('/account/' . Yii::app()->user->id), 'visible' => !Yii::app()->user->isGuest),
                array('label' => 'Login', 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest),
                array('label' => 'Logout (' . Yii::app()->user->name . ')', 'url' => array('/site/logout'), 'visible' => !Yii::app()->user->isGuest)
                ),
                ));
                ?>
            </div><!-- mainmenu
            <?php if (isset($this->breadcrumbs)): ?>
                <?php
                $this->widget('zii.widgets.CBreadcrumbs', array(
                    'links' => $this->breadcrumbs,
                ));
                ?><!-- breadcrumbs -->
            <?php endif ?>

            <?php echo $content; ?>

            <div class="clear"></div>

            <div id="footer">
                Copyright &copy; <?php echo date('Y'); ?> Created by <?= Yii::app()->params['creator'] ?>.<br/><!-- ni footer tu...ejas la...kalau xnk buang-->
                All Rights Reserved.<br/>

            </div><!-- footer -->

        </div><!-- page -->

    </body>
</html>